{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flask.serviceAccountName" . }}
  labels:
{{ include "flask.labels" . | indent 4 }}
{{- end -}}
